## START: Set by rpmautospec
## (rpmautospec version 0.6.1)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/stretchr/testify
%global goipath         github.com/stretchr/testify
Version:                1.9.0

%gometa

%global common_description %{expand:
Golang set of packages that provide many tools for testifying
that your code will behave as you intend.

Features include:

 - Easy assertions
 - Mocking
 - Testing suite interfaces and functions}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md EMERITUS.md MAINTAINERS.md README.md

Name:           golang-github-stretchr-testify
Release:        %autorelease
Summary:        Toolkit with common assertions and mocks

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1


%install
%gopkginstall

%if %{with check}
%check
%ifarch %{ix86} %{arm} s390x
# TestFailfastSuiteFailFastOn fails on i686 and s390x
for test in "TestFailfastSuiteFailFastOn" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%endif
%gocheck
%endif

%gopkgfiles

%changelog
* Mon May 13 2024 Martin Magr <mikel@olasagasti.info> - 1.9.0-1
- Fedora sync

* Thu Mar 07 2019 Yaakov Selkowitz <yselkowi@redhat.com> - 1.2.2-3
- Enable s390x build for RHEL 8

* Wed Mar 06 2019 Lon Hohberger <lon@redhat.com> - 1.2.2-2
- Rebuild for new architectures

* Thu Dec 13 2018 Alfredo Moralejo <amoralej@redhat.com> - 1.2.2-1
- Update to upstream v1.2.2

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 1.1.4-0.2.git69483b4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Tue Sep 12 2017 Jan Chaloupka <jchaloup@redhat.com> - 1.1.4-0.1.git69483b4
- Update to upstream v1.1.4
  resolves: #1490397

* Wed Aug 02 2017 Fedora Release Engineering <releng@fedoraproject.org> - 1.0-0.11.git976c720
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Binutils_Mass_Rebuild

* Wed Jul 26 2017 Fedora Release Engineering <releng@fedoraproject.org> - 1.0-0.10.git976c720
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Mass_Rebuild

* Thu Mar 16 2017 Jan Chaloupka <jchaloup@redhat.com> - 1.0-0.9.git976c720
- Bump to upstream 976c720a22c8eb4eb6a0b4348ad85ad12491a506
  related: #1246684

